name: Update

on:
  schedule:
    - cron: "7 18 * * *"
  workflow_dispatch: {}

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Configure cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-lint-${{ hashFiles('poetry.lock') }}
      - name: Install dependencies
        run: |
          python -m pip install poetry
          poetry install
      - name: Make changes to pull request
        run: |
             poetry run make generate
             poetry run make reformat
             poetry run make reformat

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update report
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: auto-update
          delete-branch: true
          title: '[chore] Update schema'
          body: |
            Update report
            - Updated with new schema
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            report
            automated pr
          assignees: dswistowski
          reviewers: dswistowski
          team-reviewers: |
            owners
            maintainers
          milestone: 1
          draft: false